name: PowerBI Pipeline Practice

on:
  push:
    branches:
      - main
  env:
   TENANT_ID: "my-tenant-123
   DEV_WORKSPACE: "DEV-Workspace"
   PROD_WORKSPACE: "PROD-Workspace"
   REPORT_NAME: "SalesReport.pbix"

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Build
        run: echo "Starting pipeline..."

      - name: Simulate file check
        run: echo "Found SalesReport.pbix"

  Deploy_DEV:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Connect to PowerBI
        run: echo "Connecting to Power BI Service..."

      - name: Deploy to DEV
        run: echo "Deploying to DEV workspace"

  Deploy_PROD:
    runs-on: ubuntu-latest
    needs: Deploy_DEV
    steps:
      - name: Deploy to PROD
        run: echo "Deploying to PROD workspace"
